### ISSUE TITLE
UI/UX improvements to list management

### ISSUE THREAD

**Issue by kirkbushell** [Yord/warfaster#4]
List management is a little confusing at first and so would be good to update the app to follow a more standardised approach:

1. First screen shows lists you have available, click "+" or whatever to add a new list, or click an existing list.
2. Selecting a list takes you to the list editor, where you can add/remove/configure units, as well as remove lists entirely.

**Comment by Yord** [comment]
I have revamped the UI/UX and hope it is much more approachable now.

**Comment by kirkbushell** [comment]
Good to hear from you again :)

Will check it out when I get a chance!
